# Generated by Django 5.0.1 on 2024-03-12 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_trend'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trend',
            options={'ordering': ['-occurences']},
        ),
    ]
